% ----------------------------------------------------------------------- %
% ---------- This script produces Figure 4 from the manuscript: --------- %
% ----------------------------------------------------------------------- %
% ------------------------------ 'TopoZeko: ----------------------------- %
% --------- A MATLAB function for 3-D and 4-D topographical ------------- %
% ------------------ visualisation in geosciences' ---------------------- %
% ------------------ (Zekollari, SoftwareX, 2017) ----------------------- %
% ----------------------------------------------------------------------- %
% ------------- All functions, scripts and data related ----------------- %
% ---------------- to TopoZeko are available online: -------------------- %
% ------------------ github.com/zekollari/TopoZeko ---------------------- %
% ----------------------------------------------------------------------- %

close all
clear
clc

tic
load('example_data_Morteratsch_25m.mat'); % loads BED, SUR, SUR_LAKE and VEL
disp(strcat('Time needed to load data:',num2str(toc),' seconds'))

tic
% ----------------------------------------------------------------------- %
% ------------------------ 4-D plots (Figure 4) ------------------------- %
% ----------------------------------------------------------------------- %

% Figure 4a:
TopoZeko(BED,SUR ...
    ,'extra_dimension','on' ...
    ,'title','Ice thickness (m)' ...
    ,'view_orientation',[-159.5 40] ...
    );

% Figure 4b:
TopoZeko(BED,SUR ...
    ,'bed_colors',20 ...
    ,'bed_colormap','pink' ...
    ,'bed_colormap_flipud','off' ...
    ,'cbar_colors',5 ...
    ,'D4_colormap','parula' ... % Notice that 'parula' was introduced in R2014b, if an older MATLAB version is used: use another colormap
    ,'extra_dimension','on' ...
    ,'title','Ice thickness (m)' ...
    ,'vertical_scaling',0.5 ...
    ,'view_orientation',[-151 53] ...
    );

% Figure 4c:
TopoZeko(BED,SUR_LAKE ...
    ,'bed_colormap','bone' ...    
    ,'cbar_colors',5 ...
    ,'extra_dimension','on' ...
    ,'title','Lake depth (m)' ...
    ,'view_orientation',[-159.5 40] ...
    ,'xlim',[50 250] ...
    ,'ylim',[130 260] ...
    );

disp(strcat('Time needed to produce 3 figures:',num2str(toc),' seconds'))



