% ----------------------------------------------------------------------- %
% ---------- This script produces Figure 2 from the manuscript: --------- %
% ----------------------------------------------------------------------- %
% ---------------------------------'TopoZeko: --------------------------- %
% ---------- A MATLAB function for 3-D and 4-D topographical ------------ %
% ------------------- visualisation in geosciences' --------------------  %
% -------------------- (Zekollari, Journal, Year) ----------------------- %
% ----------------------------------------------------------------------- %
% ------------- All functions, scripts and data related ----------------- %
% ---------------- to TopoZeko are available online: -------------------- %
% ------------------ github.com/zekollari/TopoZeko ---------------------- %
% ----------------------------------------------------------------------- %

close all
clear
clc

tic
load('example_data_Morteratsch_25m.mat'); % loads BED, SUR, SUR_LAKE and VEL
disp(strcat('Time needed to load data:',num2str(toc),' seconds'))

tic
% ----------------------------------------------------------------------- %
% ------------------------ 3-D+ plots (Figure 2) ------------------------ %
% ----------------------------------------------------------------------- %

% Figure 2a:
TopoZeko(BED,SUR ...
    ,'view_orientation',[-159.5 40] ...
    );

% Figure 2b:
TopoZeko(BED,SUR ...
    ,'axes','on' ...
    ,'bed_colormap_flipud','off' ...
    ,'label_size',18 ...
    ,'light_orientation',[-90 90] ...
    ,'view_orientation',[-175 64] ...
    ,'xlabel','CH1903 x-coordinate (km)' ...
    ,'xlabel_rotation',-3 ...
    ,'xvalues',[789 796] ...
    ,'ylabel','CH1903 y-coordinate (km)' ...
    ,'ylabel_rotation',85 ...
    ,'yvalues',[137.025 149] ...
    ,'zlabel','Elevation (m a.s.l.)' ...
    );

% Figure 2c:
TopoZeko(BED,SUR ...
    ,'bed_colormap_flipud','off' ...
    ,'bed_trans',0.5 ...
    ,'view_orientation',[-113 15] ...
    ,'xlim',[50 280] ...
    ,'ylim',[0 350] ...
    );

% Figure 2d:
TopoZeko(BED,SUR_LAKE ...
    ,'sur_color',[0 206/255 209/255] ... % Turquoise
    ,'vertical_scaling',0.25 ...
    ,'view_orientation',[-159.5 40] ...
    );

disp(strcat('Time needed to produce 4 figures:',num2str(toc),' seconds'))